version: '3.8'

services:
  backend:
    build: ./server
    container_name: blog-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - blog-network

  frontend:
    build: ./client
    container_name: blog-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge 