#!/bin/bash

# Create namespace
kubectl apply -f namespace.yaml

# Create secrets (update with your actual values first)
echo "Please update secrets.yaml with your actual base64 encoded values before running:"
echo "1. Base64 encode your MongoDB URI: echo -n 'your-mongo-uri' | base64"
echo "2. Base64 encode your JWT secret: echo -n 'your-jwt-secret' | base64"
echo "3. Update secrets.yaml with these values"
echo ""
read -p "Press Enter after updating secrets.yaml..."

kubectl apply -f secrets.yaml
kubectl apply -f docker-registry-secret.yaml

# Deploy backend
kubectl apply -f backend-deployment.yaml
kubectl apply -f backend-service.yaml

# Deploy frontend
kubectl apply -f frontend-deployment.yaml
kubectl apply -f frontend-service.yaml

# Deploy ingress (update domain name first)
echo "Please update ingress.yaml with your actual domain name before running:"
read -p "Press Enter after updating ingress.yaml..."
kubectl apply -f ingress.yaml

# Check deployment status
echo "Deployment completed! Checking status..."
kubectl get pods -n blog-app
kubectl get services -n blog-app
kubectl get ingress -n blog-app 