apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker config - replace with your actual base64 encoded config
  .dockerconfigjson: <base64-encoded-docker-config> 