apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual base64 encoded values
  mongo-uri: <base64-encoded-mongo-uri>
  jwt-secret: <base64-encoded-jwt-secret> 